version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "automated"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "ci"
      - "automated"
